#!/usr/bin/env bash

reg-alias() {
  local module_dir dotfiles_root dir file
  module_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
  dotfiles_root="$(cd "$module_dir/../../.." && pwd)"
  dir="$dotfiles_root/bash/modules/user"
  file="$dir/90-custom-aliases.bash"

  if [[ $# -eq 0 ]]; then
    echo "usage: reg-alias <name=command...>"
    return 1
  fi

  mkdir -p "$dir"

  if [[ ! -f "$file" ]]; then
    {
      echo "#!/usr/bin/env bash"
      echo "# Auto-generated by reg-alias"
      echo ""
    } > "$file"
  fi

  local line name cmd ts cmd_esc
  line="$*"

  if [[ "$line" != *"="* ]]; then
    echo "[ERROR] expected name=command... (missing '='): $line"
    return 2
  fi

  name="${line%%=*}"
  cmd="${line#*=}"

  if [[ -z "$name" || -z "$cmd" ]]; then
    echo "[ERROR] empty name or command: $line"
    return 2
  fi

  if grep -Eq "^[[:space:]]*alias[[:space:]]+${name}=" "$file"; then
    echo "[ERROR] alias already registered: $name"
    return 3
  fi

  ts="$(date '+# [%Y-%m-%d %H:%M]')"
  cmd_esc=${cmd//\'/\'\\\'\'}

  {
    echo ""
    echo "$ts"
    printf "alias %s='%s'\n" "$name" "$cmd_esc"
  } >> "$file"

  echo "OK registered alias: $name"

  builtin alias "$name=$cmd"
  echo "active now: $name"

  if git -C "$dotfiles_root" rev-parse --is-inside-work-tree >/dev/null 2>&1; then
    git -C "$dotfiles_root" add "bash/modules/user/90-custom-aliases.bash"
    git -C "$dotfiles_root" commit -m "reg-alias: $name" >/dev/null 2>&1 || true
  fi
}

aliases() { reg-alias "$@"; }
