#!/usr/bin/env bash

reg-export() {
  local module_dir dotfiles_root dir file
  module_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
  dotfiles_root="$(cd "$module_dir/../../.." && pwd)"
  dir="$dotfiles_root/bash/modules/user"
  file="$dir/80-custom-exports.bash"

  if [[ $# -eq 0 ]]; then
    echo "usage: reg-export <NAME=VALUE...>"
    return 1
  fi

  mkdir -p "$dir"

  if [[ ! -f "$file" ]]; then
    {
      echo "#!/usr/bin/env bash"
      echo "# Auto-generated by reg-export"
      echo ""
    } > "$file"
  fi

  local line name value ts value_esc
  line="$*"

  if [[ "$line" != *"="* ]]; then
    echo "[ERROR] expected NAME=VALUE... (missing '='): $line"
    return 2
  fi

  name="${line%%=*}"
  value="${line#*=}"

  if [[ -z "$name" ]]; then
    echo "[ERROR] empty variable name: $line"
    return 2
  fi

  if [[ ! "$name" =~ ^[A-Za-z_][A-Za-z0-9_]*$ ]]; then
    echo "[ERROR] invalid variable name: $name"
    return 2
  fi

  if grep -Eq "^[[:space:]]*export[[:space:]]+${name}=" "$file"; then
    echo "[ERROR] variable already registered: $name"
    return 3
  fi

  ts="$(date '+# [%Y-%m-%d %H:%M]')"
  value_esc=${value//\'/\'\\\'\'}

  {
    echo ""
    echo "$ts"
    printf "export %s='%s'\n" "$name" "$value_esc"
  } >> "$file"

  echo "OK registered export: $name"

  builtin export "$name=$value"
  echo "active now: $name"

  if git -C "$dotfiles_root" rev-parse --is-inside-work-tree >/dev/null 2>&1; then
    git -C "$dotfiles_root" add "bash/modules/user/80-custom-exports.bash"
    if git -C "$dotfiles_root" commit -m "reg-export: $name" >/dev/null 2>&1; then
      if git -C "$dotfiles_root" push >/dev/null 2>&1; then
        echo "pushed to origin"
      else
        echo "[WARN] commit feito, mas push falhou"
      fi
    fi
  fi
}

exports() { reg-export "$@"; }