#!/usr/bin/env bash
# Auto-generated by reg-alias


# [2026-05-27 09:36]
alias home='cd /home/avilamrs'

# [2026-05-27 09:58]
alias dotfiles='cd /home/avilamrs/.dotfiles'

# [2026-05-27 09:59]
alias data='cd /data/avilamrs'

# [2026-05-27 10:17]
alias code-space='cd /data/avilamrs/code-space'
